#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.db import connections

#UTIL
import json
import requests
import xmltodict

#from backend.djangoapps.common.views import common_sample
def common_sample():
    print("hello world")

#from backend.djangoapps.common.views import dictfetchall
def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

#from backend.djangoapps.common.views import api_coSpaces
def api_coSpaces():

    Authorization = 'Basic YWRtaW46RXRlY2hzeXN0ZW0='

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/coSpaces'
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")
    print(resDataJson['coSpaces']['@total']) #total
    print(len(resDataJson['coSpaces']['coSpace'])) #coSpace len

    for n in range( 0, len(resDataJson['coSpaces']['coSpace']) ):
        print( resDataJson['coSpaces']['coSpace'][n]['@id'] )
        print( resDataJson['coSpaces']['coSpace'][n]['name'] )
        print( resDataJson['coSpaces']['coSpace'][n]['autoGenerated'] )
        if 'uri' in resDataJson['coSpaces']['coSpace'][n]:
            print( resDataJson['coSpaces']['coSpace'][n]['uri'] )
        else:
            print('null')
        print( resDataJson['coSpaces']['coSpace'][n]['callId'] )
        print("-------------------------------------------------")
    #print(resDataJson['coSpaces']['coSpace'][0])
    #print(resDataJson['coSpaces']['coSpace'][1])
    #print(resDataJson['coSpaces']['coSpace'][2])
    #print(type(resDataJson))
    print("-------------------> DEBUG[e]")

    return resDataJson
