#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.db import connections
from django.conf import settings

#UTIL
import json
import requests
import xmltodict

#from backend.djangoapps.common.api.views import api_coSpaces
def api_coSpaces(search_str):

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/coSpaces'
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    realList = []

    print("-------------------> DEBUG[s]")
    print("total = ", resDataJson['coSpaces']['@total']) #total
    print("realTotal = ", len(resDataJson['coSpaces']['coSpace'])) #total

    for n in range( 0, len(resDataJson['coSpaces']['coSpace']) ):
        realDict = {}
        print("===========================================================")
        if resDataJson['coSpaces']['coSpace'][n]['name'].find(search_str) != -1:
            realDict['id'] = resDataJson['coSpaces']['coSpace'][n]['@id']
            realDict['name'] = resDataJson['coSpaces']['coSpace'][n]['name']
            realDict['autoGenerated'] = resDataJson['coSpaces']['coSpace'][n]['autoGenerated']
            if 'uri' in resDataJson['coSpaces']['coSpace'][n]:
                realDict['uri'] = resDataJson['coSpaces']['coSpace'][n]['uri']
            else:
                realDict['uri'] = 'null'
            realDict['callId'] = resDataJson['coSpaces']['coSpace'][n]['callId']
            realList.append(realDict)
            print("find!!!")
            print(realDict['name'])
        else:
            print("not found")

        print("===========================================================")
    print("-------------------> DEBUG[e]")

    print("realList = ", realList)

    return realList

#from backend.djangoapps.common.api.views import api_coSpaceId
def api_coSpaceId(id):

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/coSpaces/' + id
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")
    print(resDataJson['coSpace']['@id'])
    print(resDataJson['coSpace']['name'])
    print(resDataJson['coSpace']['autoGenerated'])
    print(resDataJson['coSpace']['uri'])
    print(resDataJson['coSpace']['callId'])
    print(resDataJson['coSpace']['passcode'])
    print(resDataJson['coSpace']['secret'])
    print(resDataJson['coSpace']['defaultLayout'])
    print("-------------------> DEBUG[e]")

    return resDataJson

#from backend.djangoapps.common.api.views import api_activeCall
def api_activeCall():

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/calls'
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")

    print("-------------------> DEBUG[e]")

    return resDataJson

#from backend.djangoapps.common.api.views import api_templateLegPro
def api_templateLegPro(id):

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/callLegProfiles/' + id
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")

    print("-------------------> DEBUG[e]")

    return resDataJson

#from backend.djangoapps.common.api.views import api_templatePro
def api_templatePro(id):

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/callProfiles/' + id
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")

    print("-------------------> DEBUG[e]")

    return resDataJson

#from backend.djangoapps.common.api.views import api_mornitoringStatus
def api_mornitoringStatus():

    Authorization = settings.AUTHORIZATION

    # requests GET
    url = 'https://14.63.53.22:449/api/v1/system/status'
    headers = {
        'Authorization': Authorization
    }
    r = requests.get(url, headers=headers, verify=False)
    resData = str(r.text)

    # xml to json
    o = xmltodict.parse(resData)
    resData = json.dumps(o)
    resDataJson = json.loads(resData)

    print("-------------------> DEBUG[s]")

    print("-------------------> DEBUG[e]")

    return resDataJson
